import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { sql } from '@/lib/db'

type DateLike = string | Date | null | undefined
type LastSyncRun = { id:number; status:string; from_date:DateLike; to_date:DateLike; records_fetched:number|null; records_inserted:number|null; records_updated:number|null; records_skipped?:number|null; finished_at:DateLike; error_message:string|null }
type SummaryCounts = { total_appointments:number; total_clients:number; appointments_without_client:number; upcoming_appointments:number; cancelled_appointments:number }
type NameCountRow = { label: string; count: number }
type MonthCountRow = { month: DateLike; count: number }

const formatDateTime = (v:DateLike)=>{ if(!v) return '—'; const d=v instanceof Date?v:new Date(v); return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(d) }
const formatDate = (v:DateLike)=>{ if(!v) return '—'; const d=v instanceof Date?v:new Date(String(v).includes('T')?String(v):`${v}T00:00:00.000Z`); return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('en-US',{dateStyle:'medium'}).format(d) }

async function hasRecordsSkippedColumn(){ const r=await sql`select exists (select 1 from information_schema.columns where table_schema='public' and table_name='acuity_sync_runs' and column_name='records_skipped') as has_records_skipped`; return Boolean((r[0] as {has_records_skipped:boolean}|undefined)?.has_records_skipped) }

async function syncAcuityAction(){
  'use server'
  const now=new Date(); const from=new Date(now); from.setUTCDate(from.getUTCDate()-30); const to=new Date(now); to.setUTCDate(to.getUTCDate()+180)
  const fromYmd=from.toISOString().slice(0,10); const toYmd=to.toISOString().slice(0,10)
  const h=await headers(); const host=h.get('x-forwarded-host')??h.get('host'); const proto=h.get('x-forwarded-proto')??'http'
  if(!host) throw new Error('Unable to resolve host for sync request.')
  const response=await fetch(`${proto}://${host}/api/acuity/sync?from=${fromYmd}&to=${toYmd}`,{method:'GET',cache:'no-store'})
  if(!response.ok){ const payload=(await response.json().catch(()=>null)) as {message?:string}|null; throw new Error(payload?.message??`Acuity sync failed with status ${response.status}.`) }
  redirect('/acuity/dashboard')
}

export default async function AcuityDashboardPage(){
  const hasSkipped=await hasRecordsSkippedColumn()
  const lastSyncRows=hasSkipped?await sql`select id,status,from_date,to_date,records_fetched,records_inserted,records_updated,records_skipped,finished_at,error_message from acuity_sync_runs order by started_at desc limit 1`:await sql`select id,status,from_date,to_date,records_fetched,records_inserted,records_updated,finished_at,error_message from acuity_sync_runs order by started_at desc limit 1`
  const lastSync=(lastSyncRows[0] as LastSyncRun|undefined)??null
  const summary=(await sql`select (select count(*)::int from acuity_appointments) as total_appointments,(select count(*)::int from acuity_clients) as total_clients,(select count(*)::int from acuity_appointments where client_id is null) as appointments_without_client,(select count(*)::int from acuity_appointments where appointment_datetime >= now()) as upcoming_appointments,(select count(*)::int from acuity_appointments where canceled is true) as cancelled_appointments`)[0] as SummaryCounts
  const topClients=(await sql`select coalesce(nullif(trim(concat_ws(' ', c.first_name, c.last_name)), ''), c.email, a.client_email, 'Unknown client') as label, count(*)::int as count from acuity_appointments a left join acuity_clients c on c.id = a.client_id group by 1 order by count(*) desc, 1 asc limit 10`) as NameCountRow[]
  const byRoom=(await sql`select coalesce(nullif(calendar_name, ''), 'Unknown calendar') as label, count(*)::int as count from acuity_appointments group by 1 order by count(*) desc, 1 asc`) as NameCountRow[]
  const byType=(await sql`select coalesce(nullif(appointment_type_name, ''), 'Unknown type') as label, count(*)::int as count from acuity_appointments group by 1 order by count(*) desc, 1 asc`) as NameCountRow[]
  const byAppointmentMonth=(await sql`select date_trunc('month', appointment_datetime) as month, count(*)::int as count from acuity_appointments where appointment_datetime is not null group by 1 order by 1 desc`) as MonthCountRow[]
  const byCreatedMonth=(await sql`select date_trunc('month', created_datetime) as month, count(*)::int as count from acuity_appointments where created_datetime is not null group by 1 order by 1 desc`) as MonthCountRow[]
  const recentRunsRows=hasSkipped?await sql`select status,from_date,to_date,records_fetched,records_inserted,records_updated,records_skipped,started_at,finished_at,error_message from acuity_sync_runs order by started_at desc limit 10`:await sql`select status,from_date,to_date,records_fetched,records_inserted,records_updated,started_at,finished_at,error_message from acuity_sync_runs order by started_at desc limit 10`

  return <div className="min-h-screen bg-zinc-950 text-zinc-100"><main className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-6 py-12 sm:px-10 lg:px-12"><header className="space-y-2"><h1 className="text-3xl font-semibold tracking-tight text-zinc-50 sm:text-4xl">Acuity Dashboard</h1><p className="text-sm text-zinc-400 sm:text-base">Synced booking and client data from Acuity</p></header>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-5"><h2 className="text-lg font-medium">Last Sync</h2>{lastSync?<dl className="mt-4 grid gap-3 text-sm text-zinc-300 sm:grid-cols-2 lg:grid-cols-3"><div><dt className="text-zinc-400">Status</dt><dd>{lastSync.status}</dd></div><div><dt className="text-zinc-400">From</dt><dd>{formatDate(lastSync.from_date)}</dd></div><div><dt className="text-zinc-400">To</dt><dd>{formatDate(lastSync.to_date)}</dd></div><div><dt className="text-zinc-400">Records fetched</dt><dd>{lastSync.records_fetched??0}</dd></div><div><dt className="text-zinc-400">Records inserted</dt><dd>{lastSync.records_inserted??0}</dd></div><div><dt className="text-zinc-400">Records updated</dt><dd>{lastSync.records_updated??0}</dd></div>{hasSkipped?<div><dt className="text-zinc-400">Records skipped</dt><dd>{lastSync.records_skipped??0}</dd></div>:null}<div><dt className="text-zinc-400">Finished at</dt><dd>{formatDateTime(lastSync.finished_at)}</dd></div>{lastSync.status==='failed'?<div className="sm:col-span-2 lg:col-span-3"><dt className="text-zinc-400">Error message</dt><dd className="text-red-300">{lastSync.error_message??'Unknown error'}</dd></div>:null}</dl>:<p className="mt-3 text-sm text-zinc-400">No sync runs found yet.</p>}</section>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-5"><h2 className="text-lg font-medium">Manual Sync</h2><p className="mt-1 text-sm text-zinc-400">Syncs bookings from 30 days ago to 180 days ahead.</p><form action={syncAcuityAction} className="mt-4"><button type="submit" className="rounded-md border border-zinc-600 bg-zinc-800 px-4 py-2 text-sm font-medium text-zinc-100 hover:bg-zinc-700">Sync latest Acuity data</button></form></section>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Total appointments in DB',summary.total_appointments],['Total clients in DB',summary.total_clients],['Appointments without linked client',summary.appointments_without_client],['Upcoming appointments count',summary.upcoming_appointments],['Cancelled appointments count',summary.cancelled_appointments]].map(([label,value])=><article key={String(label)} className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-4"><h3 className="text-xs uppercase tracking-wide text-zinc-400">{label}</h3><p className="mt-2 text-2xl font-semibold">{value}</p></article>)}</section>
  <section className="grid gap-4 lg:grid-cols-2"><InsightTable title="Top 10 clients by number of appointments" rows={topClients} firstColumnLabel="Client" secondColumnLabel="Appointment count" /><InsightTable title="Appointments by room/calendar" rows={byRoom} firstColumnLabel="Calendar" secondColumnLabel="Appointment count" /><InsightTable title="Appointments by appointment type" rows={byType} firstColumnLabel="Appointment type" secondColumnLabel="Appointment count" /><MonthTable title="Appointments by appointment month" rows={byAppointmentMonth} secondColumnLabel="Appointment count" /><MonthTable title="Bookings created by month" rows={byCreatedMonth} secondColumnLabel="Booking count" /></section>
  <section className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-5 overflow-x-auto"><h2 className="text-lg font-medium">Recent sync runs</h2><table className="mt-4 min-w-full divide-y divide-zinc-800 text-left text-sm"><thead className="text-zinc-300"><tr><th className="px-3 py-2 font-medium">Status</th><th className="px-3 py-2 font-medium">From</th><th className="px-3 py-2 font-medium">To</th><th className="px-3 py-2 font-medium">Fetched</th><th className="px-3 py-2 font-medium">Inserted</th><th className="px-3 py-2 font-medium">Updated</th>{hasSkipped?<th className="px-3 py-2 font-medium">Skipped</th>:null}<th className="px-3 py-2 font-medium">Started</th><th className="px-3 py-2 font-medium">Finished</th><th className="px-3 py-2 font-medium">Error message</th></tr></thead><tbody className="divide-y divide-zinc-800 text-zinc-200">{(recentRunsRows as Array<Record<string,string|number|null>>).map((run,idx)=><tr key={`${run.status??'run'}-${idx}`}><td className="px-3 py-2">{String(run.status??'—')}</td><td className="px-3 py-2">{formatDate((run.from_date as string|null)??null)}</td><td className="px-3 py-2">{formatDate((run.to_date as string|null)??null)}</td><td className="px-3 py-2">{Number(run.records_fetched??0)}</td><td className="px-3 py-2">{Number(run.records_inserted??0)}</td><td className="px-3 py-2">{Number(run.records_updated??0)}</td>{hasSkipped?<td className="px-3 py-2">{Number(run.records_skipped??0)}</td>:null}<td className="px-3 py-2">{formatDateTime((run.started_at as string|null)??null)}</td><td className="px-3 py-2">{formatDateTime((run.finished_at as string|null)??null)}</td><td className="px-3 py-2 text-red-300">{run.status==='failed'?String(run.error_message??'Unknown error'):'—'}</td></tr>)}</tbody></table></section>
  </main></div>
}

function InsightTable({title,rows,firstColumnLabel,secondColumnLabel}:{title:string;rows:NameCountRow[];firstColumnLabel:string;secondColumnLabel:string}){return <section className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-5 overflow-x-auto"><h2 className="text-lg font-medium">{title}</h2><table className="mt-3 min-w-full divide-y divide-zinc-800 text-left text-sm"><thead className="text-zinc-300"><tr><th className="px-3 py-2 font-medium">{firstColumnLabel}</th><th className="px-3 py-2 font-medium">{secondColumnLabel}</th></tr></thead><tbody className="divide-y divide-zinc-800 text-zinc-200">{rows.length===0?<tr><td colSpan={2} className="px-3 py-3 text-zinc-400">No data yet.</td></tr>:rows.map((row)=><tr key={row.label}><td className="px-3 py-2">{row.label}</td><td className="px-3 py-2">{row.count}</td></tr>)}</tbody></table></section>}
function MonthTable({title,rows,secondColumnLabel}:{title:string;rows:MonthCountRow[];secondColumnLabel:string}){return <InsightTable title={title} rows={rows.map((r)=>({label:formatDate(r.month),count:r.count}))} firstColumnLabel="Month" secondColumnLabel={secondColumnLabel} />}
